---
- name: set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- name: pre-configure
  import_tasks: pre-configure.yml
  tags:
    - action:pre-configure

- name: install
  import_tasks: install.yml
  tags:
    - action:install

- name: configure
  import_tasks: configure.yml
  tags:
    - action:configure

- name: service
  import_tasks: service.yml
  tags:
    - action:service
