---
- name: ensure firewalld is running and enabled on boot
  ansible.builtin.systemd:
    name: "{{ firewalld_service_name }}"
    state: started
    enabled: yes
  when: firewalld_service_started

- name: ensure firewalld is stop and enabled on boot
  ansible.builtin.systemd:
    name: "{{ firewalld_service_name }}"
    state: stopped
    enabled: no
  when: not firewalld_service_started
